apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: simple-github-repo
  title: Simple GitHub Repo Template
  description: Creates a new GitHub repository with a README
spec:
  owner: user:guest
  type: service

  parameters:
    - title: Repository Details
      required:
        - repoName
        - owner
      properties:
        repoName:
          type: string
          title: Repository Name
        owner:
          type: string
          title: GitHub Organization/User
          description: GitHub org or username to create the repo under

  steps:
    - id: publish
      name: Create GitHub Repo
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: Repo created via Backstage template
        repoUrl: github.com?owner=${{ parameters.owner }}&repo=${{ parameters.repoName }}
        defaultBranch: main
        files:
          - path: README.md
            content: |
              # ${{ parameters.repoName }}
              This repository was scaffolded using a Backstage template.
          - path: catalog-info.yaml
            content: |
              apiVersion: backstage.io/v1alpha1
              kind: Component
              metadata:
                name: ${{ parameters.repoName }}
                description: A simple repo created via Backstage
              spec:
                type: service
                owner: user:guest
                lifecycle: experimental

    - id: register
      name: Register in Backstage
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: catalog-info.yaml  
  output:
    links:
      - title: GitHub Repository
        url: ${{ steps.publish.output.remoteUrl }}
