apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: simple-github-repo1
  title: Simple GitHub Repo Template
  description: Creates a new GitHub repository with a README
spec:
  owner: user:guest
  type: service

  parameters:
    - title: Repository Details
      required:
        - repoName
        - owner
      properties:
        repoName:
          type: string
          title: Repository Name
        owner:
          type: string
          title: GitHub Organization/User
          description: GitHub org or username to create the repo under

  steps:
    - id: fetch-template-files
      name: Fetch Template Files
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{ parameters.repoName }}

    

    
  output:
    links:
      - title: GitHub Repository
        url: ${{ steps.publish.output.remoteUrl }}
