apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: simple-github-repo2
  title: Create GitHub Repo Template
  description: Creates a new GitHub repository with a README
spec:
  owner: user:guest
  type: service

  parameters:
    - title: Repository Details
      required:
        - repoName
        - owner
      properties:
        repoName:
          type: string
          title: Repository Name
        owner:
          type: string
          title: GitHub Organization/User
          description: GitHub org or username to create the repo under

  steps:
    - id: fetch-template-files
      name: Fetch Template Files
      action: fetch:template
      input:
        url: ../skeleton
        values:
          name: ${{ parameters.repoName }}

    - id: log-debug-info
      name: Log Inputs
      action: debug:log
      input:
        message: |
          Logging Inputs:
          Repo Name: ${{ parameters.repoName }}
          Owner: ${{ parameters.owner }}

    - id: publish
      name: Create GitHub Repo
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: Repo created via Backstage template
        repoUrl: github.com?owner=${{ parameters.owner }}&repo=${{ parameters.repoName }}
        defaultBranch: main

    - id: register
      name: Register
      action: catalog:register
      input:
         repoContentsUrl: ${{ steps['publish'].output.repoContentsUrl }}
         catalogInfoPath: '/catalog-info.yaml'  
    
  output:
    links:
      - title: GitHub Repository
        url: ${{ steps.publish.output.remoteUrl }}
